### PR TITLE
fix(loadOption): Wrong chunkName generated in nested imports

### LINKED ISSUE #39: subfolder support for pages
When a page is located in subfolder, the page can't be found. 

Can you tell how to support loading page in subfolder, both js and css?

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
fix(loadOption): Wrong chunkName generated in nested imports
So if you import('../Something/Somethingelse') the chunkName is Something/Somethingelse. However if
i look in webpack clientStats - its Something-Somethingelse. I replace `/` with - as long as `[request]`
isn't present in the string and `/` is.

To do this, i actually just hooked into my previous features pull request. Essentially nested imports *without* a custom magic comment are put through the `checkForNestedChunkName` if its indeed a nested chunkName, i pretty much make it the `existingMagicComment` Which literally does everything we need without adding much weight or complexity to the project 

*Im not sure of the available es6 support, have you considered creating an es6 class? there would be alot less things being passed all over the show and instance variables could be used and set in the constructor. It might simplify things even :P* let me know your thoughts - i dont mind submitting a pr

fix #39

fix(loadOption): Magic Comment importCss was renamed

After fixing the nested import bug, i refactored some logic around how the chunkname finds which way it needs to be processed. I noticed that my test failed on my previous work.

I took a closer look and it pretty much took the magic comment chunk name and not the actual one

Im currently running this branch across multiple large vertices without a hitch :)

### CODE REVIEW

File: __tests__/__snapshots__/index.js.snap [hunk 1]
```diff
@@ -224,7 +224,7 @@ _universalImport({
   id: \\"./Foo\\",
   file: \\"currentFile.js\\",
   load: () => Promise.all([import(
-  /* webpackChunkName: 'Bar' */
```
Comment (ScriptedAlchemy) [inline __tests__/__snapshots__/index.js.snap]: i fixed this, next commit over

File: __tests__/index.js [hunk 2]
```diff
@@ -25,6 +25,8 @@ pluginTester({
     'static import (with file extension)': 'import("./Foo.js")',
     'static import (string template)': 'import(`./base`)',
     'static import (string template + relative paths)': 'import(`../../base`)',
+    'static import (with relative paths + nested folder)':
+      'const obj = {component:()=>import(`../components/nestedComponent`)}; ()=> obj.component()',
```
Comment (ScriptedAlchemy) [inline __tests__/index.js:29]: So why did i make an object and a function?

Its hella hard to resolve UniversalComponent with strings placed elsewhere. I initially had one util file per folder, but it would create risk among a big company, people might import the wrong thing. 

```
<UniversalComponent component={()=>import('../components/generalUI/Slider')}/> // now it resolves from this file, keeping with the common sense ES6 way of doing things. Devs just work normally ```

Comment (faceyspacey) [reply __tests__/index.js:29]: Hey what's goin on brother, i dont know if im losing my mind or just havent been in this code in a while, but is `<UniversalComponent />` your own HoC--cuz `import()` usually occurs before *render time*.

Also, what's the main problem we're trying to solve--that automatic chunk name creation requires the same initial folder name (in this case `/components/`) in order to generate the same chunk name for identical imports from different places in the file system?

**Comment by faceyspacey** [comment]
That's weird. `/Something/Somethingelse` used to work. At the same time, there was a similar webpack issue that never got resolved where index files would have an extra hyphen, which I resolved in webpack-flush-chunks:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L198

Either way, if ur getting good results, Im merging this. U work at fiverr right!? I have used it many times in the past with great success. I'm trusting your judgement :)

File: __tests__/index.js (hunk 2 above)
Comment (ScriptedAlchemy) [reply __tests__/index.js:29]: 😂 yeah it’s your universal HOC, but my component which is a little utility. 

Pretty much the problem is that the way you demonstrated works just fine as a string. But I’ve got many files. So when I need a component, I must supply a path relative to where my utility is. That’s way I can use code completion and can also do reverse dependency lookups. It removes the manual labor of having to remember where the utility is. In the example, I’m pretty much testing import as a prop rather than string. I’ll send you a snippet so you can see what the hell im talking about. In my next PR I’ll include a test that looks more normal as well for testing nested imports. 


Sorry I know it’s confusing outta context, I’ll send you how I’m using it and I’m always open to a better way

**Comment by ScriptedAlchemy** [comment]
Yeah I was wondering why I kept getting that missing chunk error. Something like “couldn’t find a chunk by this name” 

I was mega confused because everything works normally. 

So I’ve been heavily invested in webpack core back when and before webpack 2 was released (so I know my way around it well) 

Pretty much, based on the release date  of your plugin - I’m pretty sure webpack 3 is your culprit. If you check deep down in the internal chunking mechanisms, you’ll see some changes from webpack 2 and 3, 4 continues on this path, which lead to a similar chunkname by path and relationship. I’d need to open the core again to confirm but just from historical knowledge and the natural progression it sounds like the cause.

**Comment by zackkirsh** [comment]
And yes indeed, Fiverr. You've probably already seen my jumping between accounts when replying 😂 

I recently read that you were working on consolidating the universal family unto something a little less daunting, with most of the moving parts abstracted. I think you called it `universal-render` or something. Anyways, it sounds like we are going in the same direction -  so if you'd be open to it, id be willing to join forces in your efforts. Im a strong believer in this project and would like to contribute to the open-source project as much as possible, im trying to avoid a hard fork

**Comment by faceyspacey** [comment]
Yea, there's a lot that can be done. That said, React Suspense changes a lot of things, which is one of the reasons I'm apprehensive investing time in code splitting until that comes out. 

Basically, you can do this:

```js
import { call, load } from 'universal-render'

function MyAsyncComponent(props) {
   const { Component, data } = call(load, props.page, props.params) // call is just a generic helper function to call any async suspense-oriented function
   return <Component data={data} />
}
     
```

> see: https://www.reddit.com/r/reactjs/comments/814huj/so_what_do_you_all_think_about_react_suspense/dv2cl9b/

**Comment by faceyspacey** [comment]
That all said, the next version of Redux-First Router (renamed  **Rudy**) has tons of code-splitting capabilities. I'm less worried about the babel transpilation than I was in the past, especially since Rudy won't need the synchronous `resolveWeak` stuff, as it runs asynchronously itself. So that leaves the transpilation just to generate on additional thing: `chunkName`, which in Rudy will also double as a cache key--so it's better just to be explicit. 

In short, I'm moving away from the transpilation. At least for the timebeing, as there are so many other fish to fry for Rudy.

Keep in mind Rudy, will be doing all code splitting at the route level. It's basically core to the whole concept--code splitting components aren't necessary when Rudy has you think of your whole app in near-static routes.

**Comment by zackkirsh** [comment]
Yeah, I had some concerns around what the new react versions are going to mean for the universal family. I know facebooks working on async rendering.

When it comes to transpileing, i have to agree there. I see mostly its a good way to remove the manual labor of swapping things out or writing chunknames. That being said, Id encourage keeping the resolveWeak functionality alive for cases where Rudy isn't used. I think a major achievement is route based splitting which obviously has its benefits and should serve the need of most. Depending on the scale of the applications though, i think the universal HOC is fantastic (beyond react apps too, the reporting side of it can be pretty useful). Ive not looked too much into Rudy but will take a closer look at it if theres a public repo. 

Something im beginning to dedicate time to, which was inspired by your work. Is the ability to share resources (chunks) between independent webpack builds. A growing issue I've seen develop in the FE world is micro-frontends, code isnt really shared, or if it is, it requires webpack builds being, in some way, aware of each-other during compile (Auto DLL and stuff). Im trying to conjure up a way where, at least on the FE, resources can be shared between independent architectures that consume the same chunks.

**Comment by faceyspacey** [comment]
https://github.com/faceyspacey/redux-first-router/tree/rudy-next-temp

that's the code. i just finished a month long client project, so the commits are about to roll in again and wrap Rudy up. It's so close.

As far as shared DLLs, I've actually done some basic stuff there to pre-build DLLs. The techniques included named or hashed module IDs, externals, using the `libraryTarget` webpack option to build DLLs as a big library. I forget exactly what I did recently, but I think what I did was use `externals` to point to pre-built modules that were tacked on to `window.DLL_MODULES` or something like this.

Not sure if that's what you're talking about, but what I've also been thinking about is this:

```js
<Script src='http://www.paidcomponent.com/component.js' someProp='foo'>
    <div>some child stuff</div>
</Script>
```

I wanna make ethereum-contract-based components that load over the wire, which take props and children and do stuff with it. The simplest example would be a paid charting library.

I feel like open source has taken this turn where everyone is giving everything up for free, yet we all work for our slave-masters. I'm all for a world where we work for ourselves (or as close to it as possible), while selling tid bits of our ware along the way. I feel like that's what's supposed to happen in the decentralized world we're building--we gotta get away from big employers running the show.

So I imagine a system where you can make plugins of plugins of plugins. Where each plugin pays rent (in ether) to its parent *"host"* plugin. I'm specifically re-making Redux devtools for Rudy and lots of new stuff we'll be doing. That's the business model where everything i've been building is going. So paid Redux devtools that have far more capabilities than the current one. And more importantly, you can plug additional tools into it, and pay "rent" by giving a cut to the host. You could then even have plugins in your plugin, and collect rent just the same--so long as the rent goes back up the ladder. 

As far as the `<Script />` component, that was kind of a tangent, but basically these paid ecosystems could exist in all our apps, not just an additional window that opens up and houses the redux/rudy dev tools. It goes back to what you were saying: *distributed webpack builds*--why aren't we loading components over the wire from 3rd parties?? Why aren't savvy developers taking advantage of this as a way to license their code for $???

I think a lot of it must go back to the fact that even if the code is minimized and obfuscated, people feel it's kinda cheezy to sell this code when access to "source" is available. I haven't done the research yet, but there has to be ways to secure access so users have to pay you. Wallabyjs seems to be doing it--they're shipping code to your computer. Even if someone searched through the obfuscated code, and found the "keepalive" ping that checks whether you are licensed to use the software, and hacked it, it simply wouldnt matter. Because so few developers would actually do that when ur charging only $15/month. And that said, it's likely securable in a reasonable enough way. I.e. so people keep paying a few sheckles per month for our minimized/obfuscated component, or devtools panel.

I feel like the direction the core webpack team sees for code splitting is: "Code Split Everything." And I think that's correct. I think the idea is if everything was code split, seeing spinners for every little thing would become 2nd nature to our psyche's, plus would be very fast, because it would always be a small amount of bytes. More importantly though, in this world, 3rd party libs loaded like `<Script />` would be no different than regular dynamic chunks (from the end user's perspective). And on top of that, it would become a way for developers to build together--everybody builds their own chunks, with the expectation that it will easily plug into some host. 

React components in general are the foundation of this highly *modular* dream (even though I think they are the wrong primitive for data-fetching and scene/route transitions). I think there's a lot left to be done here to create the coding of the future. ..Sometimes you see developers ask for ideas of what to build on Reddit--dude, I got 10,000 things I want to build, and only 10 hours per day. We're at a very cool point in time (perhaps we always were, and only now i can see the opportunities). There's a million things we can do to improve DX for developers the world over. A million non-pie-in-the-sky things. I dont wanna call them "incremental" because that down-plays them. But there are a million things between incremental and an "order of magnitude in DX improvement" that are out here for a squad of developers to tackle.

**Comment by ScriptedAlchemy** [comment]
@faceyspacey 

Hey James, sorry I took my time to respond... Its been a busy week.

DLL's:
So when it comes to DLLs, I already use all the external goodness. What you are talking about sounds like using the webpack dependency option and configuring a set of deps to resolve, then use libraryTarget followed with externals on the other builds, or something like that... We do the same for react and other vendor stuff thats heavily used all over the place. 

What Im talking about is something that I've found little info about... I want to have DLL's buuuut without and pre-built nonsense. Im working on a way to make many independent webpack builds (microfrontends) share resources on the frontend as if they were one big, code-split build. 

If MFE (micro frontend) A uses something like moment.js, and MFE B uses moment.js as well, let MFE B use MFE A's chunk. Now I know this could be common chunks or part of vendor.js, but thats alot of code for like one page or even just two little MFEs to now bundle into vendor.js. 

At the same time, I don't want to bundle the same thing into two MFEs when there might already be one on the page whose providing the module. I know this might be a tricky thing, but at the same time code-split SSR was a pipe-dream till a year ago (thanks dude). 

To sum it up, I want the client side to act as one and make webpack builds work together without providing context ahead of time. Something kind of like the agressiveSplitting in webpack, but in a way where LOSA systems can share already instantiated dependencies. (LOSA = Lots of Small Applications, actually super awesome when it comes to large scale separation of concerns. Its damn hard to bring down production, maybe a sidebar stops loading - critical failures are beautifully contained within their own architecture)


Ethereum Contract Components: 

Ohhh this is super cool! Ive actually built somewhat similar things (and currently messing around with B-chain ETH asset loading)

Id love to know, how do you see the props getting to the paid component (post,put,socket, or HOC where props are just passed when loaded)? Would that component also SSR its-self or just serve back a result / function to be executed?

Heres what I've been working on, and actually am releasing a trial run to production some time soon (Not to Fiverr Prod). Im sure you've heard of IPFS… ETH based p2p bit-swapping file storage. 

Anyway, im a bit of a bandwidth nut (found a great formula to reduce code size substantially more than zLib). But no matter how small (large backbone application, smaller and faster then the homepage of google), I still had to pay for that damn bandwidth or expensive services like cloudaniry. What I hacked together was a stable javascript driven - client side way to get either the users to seed assets to other users on the site, or users to act as anchors (using sockets and browser storage to actually store images, scripts, css) and serve it back to other users. I was able to bring up the dns component which meant that the client wouldn’t need a domain at all to query for peers, instead it could download images via its own dns gateway and service worker to actually act as a server. Mostly R&D but how cool would it be to have a CDN what doesn’t even need a url, you can resolve via your own gateway or anyone else who’s browser is up and running. True decentralization 

The cool thing with IPFS is you aren't just making your users carry the load. The more demand, the more third parties connected to the network help share the load. Ive been able to upload 5GB, seed it from my browser (dev mode on), and download it on another machine in another state, RIGHT FROM MY BROWSER, The second time I downloaded it, it was faster, then third, even faster and the demand propagated. At the end I was pulling it down at max capacity of my downlink (200MB/s). I then terminated the browser, killing the only seed, waited a few days and was still able to download it. Many weeks later, since nobody wanted the file, it was automatically cleaned off the network. 

I am using this system now, with a node counterpart to act as a permanent anchor, to be my CDN on a stock video site (royalty free) with about 10,000 uniques a day. Bandwidth costs should come down substantially. And as long as someone is on the site ever few days, the file pretty much lives forever. Geocities ( I think that’s the name, maybe geosites?) some 90s blogging platform. They run solely on IPFS, pretty neat! 

Im a huge fan of blockchain but haven't had many opportunities, and of course time to really pursue much else. Ive got some big interests in DAPs and decentralization in general, I feel like so much of architecture can still be considered monolithic. Relying on AWS, a CDN, or something similar where at the end of the day, as you said, why the hell can we load this over the wire and why cant a model be made where our hard work gets some kickbacks along the way. Its much better than a damn PayPal button on GitHub, or got forbid, Envato :D 


I love the idea you proposed around plugins of plugins. Sounds like `class extends PaidComponent`. A great example... universal family. 

I feel like theres so much waste in the JS world, especially as we move toward more decoupled systems. I just don't understand why webpack resources cannot be shared or over the wire. Wether I build them or load them externally, why can 5 webpack builds sit on the same page and load resources over the wire and share their dependencies with other builds on the FE. It's so fantastic to speak to someone about this who really gets it! I love that im reading through this message and grinning - saying out loud "ohhh yeahhhhh"


When it comes to selling this stuff, source thats already available. It's a tricky one and devs will likely try to hustle in its obfuscated form. As you said, there ARE ways to do this, I've theorized a few myself, and given some bigger companies I've worked with - I've been exposed to cool challenges which can kinda glob together. 

Off the top of my head, give a few of these some thought: 
-Stream it as a binary into a service-worker which can process it 
-Try something like streaming something within a specific byte-range, meaning that its always partial content
-Stream it as a LZMA binary, then install a service-worker which can execute a behind the scenes decompression of it and serve it as a blob thats then mutated after execution (I've used something similar to this before)
-Make the resource work hand in hand with the service worker or socket, some stupid ways to actually pull this off would be to either change a set of unit8array sequences every 1 min which would need to be checked against a checksum on the SW, in order for the code to run correctly, the SW would need to update the unit8array at specific byte-ranges (this seems like it could be costly).
-Another once if played around with, which has been pretty useful, create a transpiler which pretty much serves non-existent function names or a kind of dictionary. So the script would need to ask the worker or streamed socket for the definition of "Evr4w" which could be "()=>new Array()" or something like this. Sounds silly but if they copy the code, they it wont run without the lookup service to respond with what the function actually is. Not sure exactly how this would play out but, I don't see this being something impossible to accomplish. 

Again, if the price is right, and it just a little too much effort beyond a copy paste, theres few who are going to waste the time. Any dev who plans to use this at a large scale has better things to do than waste a couple $100 in dev time to look at hacking the licensing

Id love to brainstorm with you if you ever need, this stuff is cool and I love problems like this - again if you need a hand with anything, id love to be part of this awesomeness. My time limited but I can do some grunt work at the very least. Regardless, ill be closely following your work

Dude "Code Split Everything." is the way, like I've gone as far to even consider replacing all imports with import() and extending the universal HOC so it can consume dependency chains in a more automatic way. And to be honest, with SSR and loaders near everywhere, I doubt it going to be a bad experience. Ive worked on some interesting ways to preload code as well. My favorite one was a proprietary utility which could predict what a user was likely to interact with, based on the size, position, size of screen, and speed at which courser moved toward it. Theres plenty of elegant ways to prevent almost all loaders unless its superman clicking through the site. 

I assume you are speaking about apps where the whole line is hosted on your <Script> like system? I was speaking with some of my engineers today about the idea of code splitting and on the wire from a third party. One big question that came up, which I think is relevant in this context. How'd you tree shake something like this, and remove bloat from... well essentially a similar sounding architecture im trying to lay? The script works on its own, but the script should be able to behave as a chunk too, lending it resources to another chunk. If you find yourself trying to solve this, as far as im aware - if or when we DO solve it… Boom another world first. 

Anyway, this was a great message to read and reply to. Thanks for taking the time to share some insights

**Comment by faceyspacey** [comment]
I think your last sentence sums up the primary idea here:

> the script should be able to behave as a chunk too, lending its resources to another chunk

There was a guy on twitter this fall hassling the webpack team about what amounts to *distributed webpack* (he didn't get that webpack is founded in static analysis of existing code; the guy didn't know "distributed webpack" was what he was in fact getting at). The webpack guys weren't too interested.

Webpack does a lot, but as with everything, a week really investing in yourself in large projects makes them a whole lot less scary. That's not the case with me and webpack (it's still scary), but obviously others weren't so daunted (parcel, fusebox guys, etc).

So that said, webpack isn't needed for modern browsers. I'm sure you're aware, but here's some bookmarks to techniques I've been itching to try out myself:

https://medium.com/front-end-hacking/react-without-webpack-a-dream-come-true-6cf24a1ff766
https://github.com/misterfresh/react-without-webpack

There's a few others people that have written about their forays into using native es modules in the browser and skipping bundling. ..So basically, if:

- we didnt need loaders
- we didnt need es6-to-5 transpilation 
- and we didnt need bundling
We could leapfrog the webpack stage we're currently at; and then find a home for the solutions to the aforementioned problems in this inevitable *(possibly already here)* future. ...So:

- we dont need loaders cuz maybe we use Emotion or React Native Web etc for css; we can make due with manual image management in directories consumed by cloudinary etc
- chrome has basically everything in es6 we need besides `method = () => {...`, which we can live without if we have to; or we transpile in the browser
- native browser modules eliminates the need for bundling

HTTP2 basically makes the number of scripts loaded a non-issue *supposedly*. So if that's the case, whats stopping every module from being code-split by default and loaded from https://unpkg.com if it's not on your own server. For "static" imports, chrome must be waiting for them all to load in the linking phase, but what if we made them all dynamic using `import()`, and then made EVERY react component able to show a spinner if the corresponding module wasnt loaded yet. And to improve UX, we obviously use *React Suspense's* capability to essentially "catch" pending children in a smaller number of UI placeholders. That way it's not like a million async components/modules need to be paired to a spinner perfectly stylized for its respective location.

It's basically what you meant by this: 

> I've gone as far to even consider replacing all imports with import()

I mean the funny part is this is basically what the webpack team is hinting. It's what they are just dying for someone to experiment with and actually pull off. It would be many tiers deep worth of child chunks. If you read sokra's explanation on how the new "commons" stuff works, you'll see lots of preparation for a heavily code split world: https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693#configurate-cache-groups

But the messed up part is this: if we took this all the way down to every single module, making full use of HTTP2, webpack isn't needed anymore. The bundling is automatic. The code splitting is automatic. And the UI spinner stuff is handled with ease thanks to React suspense. The concept they are promoting--when pushed to the max--essentially erases the need for them/webpack in modern browsers lol.

### Now, what about *"lending resources to another chunk"*?

The first thought that comes to mind is simply now that there are **no more chunks** lol, `import()` just needs to be run in such a way that it checks the browser cache. And perhaps Chrome is already doing that as part of their native modules stuff. Otherwise, our system should be able to use a custom function which checks the cache. And we're done. Story over.

The tradeoff we have to make are people with crappy browsers. But truthfully im so tired of that crap. Show em a link to download a good browser, and move on with our lives. AND, if we're building developer tools (which is the only market I know anymore), it simply doesnt matter.

On a side note (and dont tell anyone), I think im done with SSR. When i need it for an app Im working on (which wont be for a long while), I'm thinking I'll just use a pre-render service or something like the following which I just saw a few days ago: https://github.com/stereobooster/react-snap

The real reason I'm done with it is the same reason I dont wanna use webpack anymore: build time. I miss the days of instant evaluation. Dude, this feedback needs to be instant. I was hired recently to take a monolithic rails app from a sprockets/browserify setup to webpack. And more specifically to take build times from like a minute down to .5-2 seconds. I successfully was able to do it, but it took weeks. ..If you've played with CodeSandBox, in simple setups, you probably confronted bascally instant evaluation. It's great. Where it breaks down is simply: you can't code big apps in code sandbox or chrome becomes janky. You can't code small apps there. You can only code petite demos. Which is why @misterfresh 's react-without-webpack is something that gotta be taken seriously--especially for those fortunate enough to be building for developers or other markets that only use new browsers. 

Lastly, since it's all about native apps, I've been wondering why are we compiling babel for React Native. I know Android has an older version of Node they're using. But we should be able to use the latest node with experimental harmony modules turned on etc. I mean I'm sure we can if we customize a few internals. We gotta get away from this compiling stuff, source-maps, etc, *since we can*. We arent clojurescript. We are the target language of these platforms for god's sake.

Whenever I use the chrome console, Im always surprised at how much ES6 is available to me these days. I think it was just one thing that was missing a year ago: `...spread`. It's there now. Before we even carve up the time to get started on this we'll be able to use `method = () =>` (I forget what thats called).

The best part about chrome is the runtime. Specifically the feeling that autocomplete in the console gives you. You feel like you're dealing with something that's alive and knowledgable about what you're coding. It's too bad that actually coding in chrome (whether in CodeSandBox or the *Sources* tab isn't performant enough). ..Chris Granger's Light Table used to sync to chrome and bring back those chrome console evaluations into its ClojureScript IDE.

But anyway, let's not go too crazy when there's a low hanging fruit here we certainly could setup for a developer-focused product. Basically, we gotta do some reconnaissance and figure out if there are any caveats/limitations to this approach: https://github.com/misterfresh/react-without-webpack

The main one that comes to mind is: *is there a limit to how many modules/scripts can simultaneously be loaded before perf degrades?*

Now that said, it really highlights the strength of how we wanna build things: code-split everything and load as little as possible, while re-using as much as possible. So that basically leaves you loading React, Redux, Redux-First Router, the usual suspects, and like 5-20 react components/modules of your own. Then from there after, it's a fraction of that as you navigate the app. In short, if done right, you aren't sending that much on first load, and no more on future route transitions. I think it will work nicely. The guy who created `react-without-webpack` had a bunch of other things he had to do to get DX right, but none seemed too outlandish. 

----

Me personally, I gotta finish my current mission: Rudy, Remixx (mobx + redux + redux modules + no `connect` hoc), docs site for *Respond Framework* which is based on those 2 packages + tasks/codeGen pillar (I think about it as React's "Rails Moment"). There's so many goodies I got just in Rudy that I'm about to unload. 8 months of 75% of my time of work.

Here's the slogan: "Don't just React, Respond"

Brotha, whats comin got it goin on. The next step for the React/JS application development ecosystem. 

When I released my tools last summer, I failed to get as much attention as I could. And then like a turtle i put my head back into my shell and kept working on the next set of tools, which started out small, and as the vision unfolded I vanished too long. I wont let that happen this time. And more importantly, I have just far more than I had last summer. Rudy can do some insane stuff. It has its own middleware api. It has various middleware already. Its rebuilt over and over to be the best. Perfectionism at its finest. A luxury/curse I was fortunate enough to have this past year. But there's so much more I cant even describe right here. I'll describe one: a first: full knowledge of the browser history stored in state. You know, that history whose `entries` and `index` we cant get access to. To do this wasnt simple. Its why nobody has this. Rudy has it. It opens up a whole lot of doors for Navigators in the browser--something we collectively have given up on. ..The middleware is Koa's middleware, which is Redux's middleware if it was async basically. First class support for canceling route changes. In fact all route changes are a request to do so, which are only committed if middleware (or route thunks/sagas/observables/etc) dont exit early (i.e. return false). In short, the whole thing is built on a "request/commit" model, instead of the browser URL changing and ur shit out of luck. Yes, even when you use the browser's back/next buttons directly. 

It's a holistic rewrite of what the ultimate client side router would look like coupled to a global state store. There's no more `payload` in your actions. It's `params`, `query`, `hash`, `basename`, etc. I mention that just to paint "holistic" aspect of the picture. Still, just scratching the surface of features. Let me give u some that have a higher *wow* factor: u can code split routes during route transitions, wait for the reducer, component and parts of the route itself, to come over the wire, before triggering your `onEnter` thunk, or your saga, or observable, or apollo graphql. Code splitting as a first class concern. But more importantly, apollo graphql is front and center. Forget thunks. Use observables for the few fancy autocompletes and whatnot you have. There's an Apollo middleware which stores all your models in Redux state properly. Apollo has never had good Redux coordination. We do it differently: we take incoming apollo models and deep compare them to what you have and only if the object is different do we trade out references, thereby reducing the number of re-renderings. In most cases, it takes 0ms. Those Apollo HoCs and render props components are not what we're doing here. The dream has always been:

`app = f(state)`, and we use components as templates 90% of the time.

React is the "low level" API, and you should rarely use it, except for switches, modals, and in 3rd party libraries that offer similar. So no lifecycles, 80% functional components, use `dispatch(setState())` to set state on a route. 

It's back to the good old days of server-side MVCs, but client side where UXEX (user experience expectations) is high. Code we write now is crap: 4 nested hocs: `withRouter`, `connect`, `graphql`, something from recompose. OR as of 2018, basically the equivalent in super indented render props-based component usages. It's impossible to manage this code. 

React has been the modular revolution of UI development. But it's largely been "vertical." React development is missing a "horizontal" primitive. That primitive is "routes." 

Rudy is all about tacking all sorts of shit on those `route` objects that manage what happens when you transition between component trees ("horizontal"). :)

I got a huge article coming at launch, but ive been working on the pitch and how to phrase this in my head for a long time now. 

There's talk about how with Suspense "bottom up routing" will become the norm. Well, it already is. That's what React Route 4 is. But it's essentially a Rails conventions-based hack when you glue a nested UI by path segments--you know, like how the same UI is used for a modal in one place and as a *page* in another, and where what glues them together is the `match.url` of the parent route. It's a small thing, but basically as far as the "bottom up routing" thing goes, the idea is that with Suspense you can kinda catch route transitions higher up the tree and do data fetching and other side effects as child routes load. We havent seen this yet, cuz its not officially out yet, but i dont think its the right way.

Going back to static routes is kinda like going back to static typing from dynamic typing. And its important here: to the end user these routes are static; you only have a precise set of URLs that can be visited. Making them willy nilly as you nest your components leads to no structure. Ad hoc mess everywhere. Have you seen these apps! Im a mentor on codementor: http://codementor.io/faceyspacey , i have.

[this right here is where my pitch needs major work, i gotta explain why the current way of react development (over usage of hocs, render props, infinite nesting) is essentially complete and utter crap compared to the *separation of concerns* that static routes + global state stores offers]

..The achilles heal of this approach is that Redux isnt modular. When was the last time u saw a "Redux module." What is a redux module even? A redux module is far more than namespaced state keys. At its core its bindings between components and reducers. Eg:

```js
const Component = (props, state, actions) => {
    return <h1>{state.anything}</h1>
}

const reducer = (state, action) => action.something || state

export default createRemixxModule({
   reducer,
   Component,
   types: ['FOO', 'BAR']
})
```

What does this actually do? Well, for one it can be a 3rd party lib, or be a component re-used across apps in your organization. `anything` will never conflict. In fact, when it's loaded (i.e. when the component is dynamically imported), `replaceReducer` is called, and we get `anything-123hash456` as the state key that appears in the redux dev tools.

We call it a "binding" because within the component definition itself, it can refer to `anything` without the hash. The same goes for actions, etc. 

The real secret sauce though is that reducers now are being added/removed from redux (um *remixx*) everywhere. 

----
So "redux modules" is the achilles of the static route + global state store approach I've been pushing. Not anymore. ...It's also likely one of the reasons why the creator of Redux has become component-obsessed. The modularity of components is key. It's key for testing. It's key for so many reasons.

---

You'll also notice that `state` is now the 2nd arg to component. Yup. That's really the key signifier of React leveling up to Rails status. No more `connect`. None of those hocs are needed in fact since the router is coupled to the global state store (routing state), since apollo is integrated as well (domain state), and UI state was already there. And no usage of `setState` unless ur creating a non-application-specific "widget" or complex "brand widget."

Ur basically always passing around that `state` "BALL." That's what I call--a ball. It's always readily available. It's none of this angular/mobx crap where ur making class methods reactive. It's all highly testable as pure functions using native data structures, etc. And now it's all modular--your app can grow so big and you can now put it in another folder, create a 2nd part of your app in an adjacent folder, and then create a tiny host at the top which has things like user auth reducers/components etc, which pass the user info as props to your redux moduralized sub-apps. This is hard to describe without samples--im reaching here, cuz here's the punchline:

I need help--from someone that gets it. And I got ether. Your a passionate skilled developer. 

The dream is this: everyone building their own apps that make money. I dont wanna be nobody's boss. I want to work with passionate developers across shared/adjacent tools, sharing each other's customers, while each selling something unique. It's not a zero sum world. 

Im gonna build the paid redux devtools host. That's the final thing. Rudy's almost out and that's like 75% of this whole thing. Im looking to do some very specific things, and I've been lookin to do it before our conversation: help a top notch developer transition to running their own business, with the goal being to build the other apps in the devtools host. But with a special perk that future plugin authors wont get: upfront $ to smooth the transition over; basically a salary paid to build their plugin + work on some of the supporting open source infrastructure (remixx being the primary one; docs site; tasks/codeGen system; awesome graphql resolver solution). So it would be like 50% working on this stuff and 50% working on your plugin, which can be anything (and I got a long list of ideas). 33% cut back up the ladder is the rate I've pretty much zeroed in on for all plugin authors. But the ethereum contract should allow you to set your own cut that u take from plugins under u.

----
You mentioned u wanted to get in on some of this stuff! So I figured I'd lay out the real goods. I'm workin pretty much non-stop on the vision here. I'm also turning down clients right and left. I need people. Someone needs to be taking these gigs and giving me a cut lol! Ultimately diving into open source last year did work out. What's about to be shipped is gonna take that up about 10 levels. But it wont matter without numbers--there's basically 2 core principles I wanna operate by:

- the *decentralized everyone's their own boss, plugin of plugin, percentage* thing.
- strength in numbers

Regarding the second point, basically ive been a private coder for far too long. It's been stressful as fuck. I used to manage a team of like 10, like 10 years ago. Then I became a coder (got fed up being dependent on other people). Now I know I gotta branch out again and essentially trust others again. I never worked at large companies. Always essentially freelanced. I dont wanna work at a large company. I dont wanna show up to work anywhere. But I wanna bring people together to build lots of dope shit, and bring financial security to all that are involved. And I only want the best (part of why shit was so hard when I was managing developers on oDesk 10 years ago). But there's levels to this shit, and the rules of the game sometimes revert when you yourself change. Im talkin abstractly, but again Im just layin this out there for the *right person* to click with.

---

The code splitting thing is important. But taking the global state store thing all the way is the most important in my opinion. Everything (routing, domain state, code splitting, etc) coupled into super redux essentially. And then stuffed nicely into React. Plus top notch context-specific developer tools (BU$INE$$ MODEL BABY!). Those redux devtools are *cool*. They could be so much more, and people will pay. They're already used to them--what professional developer wouldnt pay $15/month for ones that are 100x better?? None.

Also, i forgot to mention, the test of the significance of this system is in fact *testing*. In fact, testability is the crowning achievement of React in general. Before that, basically the only option u had was full on screen scraping.

With the Respond Framework, it boils down to this:

> generate actions snapshot in devtools
```js
import snapAll from 'remixx'
import actions from './actions.snap'
import App from '../src/App'

describe('tests one whole portion of the app', () => {
  actions.forEach(action => {
      it(action.type, () => {
        return snapAll(App, action)
     })
  })
})
```

...So the basic idea is tests are generated from navigating the app. We can fully automate it, or partially automate it and let it be editable, etc. This is the proof that this whole system is the crowning achievement of React. ..See, here's the thing: we have `<Link />` ...which means u dont actually have to click those links--cuz if it gets embedded in the page, its `href` does. So if we trust the rudy-link package, we dont actually have to click those damn links. We can just dispatch actions and snap the resulting component tree. `snapAll` dispatches the action, takes a snapshot of it, snaps the resulting state, and snaps the resulting component tree. ...What bout thunks? There are no thunks in the traditional sense. RFR has had for a while `pathless routes` where u dispatch an action and then a thunk is called. In other words, its serializable. The same applies to sagas/observables/graphql. That means we can serialize just the array of "primary/setup route actions." If they trigger "follow up" actions, the integration tests will know they executed correctly by the resulting state and component tree. That's not a key aspect, and we could dispatch those ourselves too.

The point is that tools like react-testing-library are pushing all this old coupling to the DOM crap essentially. ..Pro companies need real browser testing + screenshots as part of their tests, for sure. The above can also be used with pupeteer. But we're just not manually clicking elements. `snapAll` can have an adapter to open real browser windows, take photos, snapshot the HTML as well, etc. If you cover a clickable button with a higher z-indexed div (so it's no longer clickable), ur shit out of luck, but that's a small tradeoff.

What about "sniping?" ...U know, the whole thing about snapshots essentially being overload and noise. That's definitely true with component tree snapshots (not with redux state, which needs to all be precise). Basically, our awesome devtools lets u see the damn snapshots, and click checkboxes next to lines that are important, and then u can re-run the tests in the future and say u only want to see if the important stuff/lines passed. U can even tag/categorize that stuff. ..Cuz the idea that "less information" is better is bullshit. U want these snapshots. U just also want a way to mark certain aspects of the snapshot higher priority. Then you make your primary snipes pass, and as you do, you can zero in on the relevant encompassing complete failing snapshot. It's now more of a process, than a simple "pass/fail." ..This all needs to be part of post-testing tooling. It needs to be an ongoing "process" rather than an outcome. It's essentially TDD for UI development, which without this basically doesnt exist.

So another one of the key aspects of the devtools is essentially test-driven React Storybook. Storybook has had some crumby testing support. I know, cuz ive worked on it: https://github.com/faceyspacey/jest-storybook-facade

But basically the way I wanna work is with wallaby running side-by-side with the exact portion of the app I'm looking at. And if you haven't seen wallabyjs, make sure you check it out. Basically, it opens a chrome tab with a list of all your tests, and for failing tests will display a diff of what's wrong in the snapshot (a feature I requested from them, and use heavily).

..So I wanna make edits and my tests re-run in the wallaby continuous test runner. Those tests are the ones above with those actions. So that also means i can click to any portion of my app (a `describe` block) and then click to any test (which corresponds to an `action`). The main thing is I can jump around between parts of my app like u can do in storybook, and when u do, ur essentially jumping between `describe` blocks and their array of actions/tests. If you navigate the app differently, you can click a button to update/re-sync your actions sequence snapshot.

Along with this, webpack should rebuild faster as its given a cue of what modules to rebuild. if ur looking at the member panel, it shouldnt be rebuilding ur public modules, or concerned with them at all. If ur running a set of actions on a small portion of the page (which is also possible), webpack should only rebuild those 3-5 components ur testing. But overall, with this approach ur less likely to use it as a style guide, and more likely to use it for larger portions of ur app. Though it must be able to facilitate both. After all, we have Remixx modules, so it's up to the developer what radius they wanna slice and dice their pizza. 

---

Anyway, the idea is u can jump from any portion of the app to another, while having state/actions all re-setup for you, and simultaneously the results of generated tests in wallaby. And also if it's not clear, any edits trigger re-runs of your tests in wallaby, even without saving; you can also do `console.log(somevar)` in your code and wallaby will show its value in the editor--so you have the "alive" instant runtime feedback of working in the chrome console essentially. 

The snaps can be generated like they already on in jest. The entire test files can be too, or they can be manually created (we'll see when we get that far). But more importantly, u can click aspects of state, and components (or lines) in your component tree snaps in the devtools to prioritize whats important. And then re-run the tests, only checking if portions of the snapshot for the given priority/tag are passing.

This is the global state store dream. Components as simple templates + automatic testing + another primary primitive: horizontal route transition objects (which by the way are essentially segues in XCode)

It's how we gotta build our apps. I have a non-developer-targeted app I've wanted to build for years now. I dont wanna build it unless im doin it like this. Im on the war path to get all this done. Once rudy is launched, the magnitude of what we already got--what value has already been created; how close percentage-wise we are to achieving this goal--will be a lot more clear.

> side note: how does passing `state` to components work without `mapStateToProps`? Well, with Proxies and a polyfill. Check this: https://codesandbox.io/s/3xn5zz44w6?module=%2Fsrc%2Fconnect%2Findex.js

That's a demo of `react-redux` made for the upcoming React Async. It's dumb simple. It uses @theKashey 's `memoize-state` lib to track which state slices to watch based on usage. We can take the concept a lot farther. Specifically to track usage within `render` itself. And thereby remove the need for `connect` altogether. The original plan is to make a simple babel plugin that takes ComponentCased functions in your `components` folder and wraps em like this:

```js
const MyComponent = (props, state, actions) => 
```
to:
```js
const MyComponent = remixConnect((props, state, actions) => ...)
```

```js
const remixConnect = component => class ConnectedComponent extends React.Component {
   // the details of re-rendering based on state changes omitted
   // but the idea is this component will get notified on the keys/slices of state used
   // in child components, and will tell the store the names of those *in-use* keys
   // and only get notified if those exact keys change (not every change).
   // So this is the opposite of the current `connect` which gets notified of everything
   // and leaves it up to `mapStateToProps` of each component to determine what to listen to
   // by value/reference changes. We can also use this to not run reducers that aren't in use.

   render() {
      return component(this.props, this.state, this.actions)
   }
}
```
----

I'm sure you have everything in your life all planned out, but hey, you never know. ..Basically I'd like to code a lot with someone toward a common goal. I can help in the most important ways to make that a possibility for the right person. Sometime in the next 5 weeks after the launch of Rudy makes the vision clear, I'll be looking to connect with other developers that believe in it :)

james@faceyspacey.com

**Comment by faceyspacey** [comment]
> Id love to know, how do you see the props getting to the paid component (post,put,socket, or HOC where props are just passed when loaded)? Would that component also SSR its-self or just serve back a result / function to be executed?

Basically, SSR isn't something I've thought of for these. They're client-only in the initial vision, and I guess if you're doing SSR you specify a placeholder. But with react async server rendering, we could wait on them like anything else I suppose.

As far as the props getting to the paid component, basically the `Script` component has a contract where once the script loads, it passes the props to the loaded child component. So much like ethereum contracts, `Script` is a container, a component *we* make. And then ecosystem component providers simple expect their component to be loaded into it and passed the other props. It's pretty simple. The 3rd party script is just es5 react code that will be evaluated into a component instance. Obviously we gotta figure things out regarding how we actually get the code. It probably shouldnt be a string returned from an API endpoint, as CORS sucks because of the OPTIONS request. Basically it should be some sort of JSONP that gets inserted as a script tag, for which we can easily get its contents. After all, we're creating the specification/contract, so we can just say that what's returned must assign its code to `window.ASYNC_CONTRACT_COMPONENTS.hashOfSrcUrl`. So that would mean  `<Script src="https://site.com/script.js" />` leads to Script's implementation requesting: `https://site.com/script.js?hashOfSrcUrl`. That way it has a deterministic hash and can be cached in browsers and CDNs well. Something like that.

The next thing--and something I havent put any thought into until now--is if unpk is hosting stuff off of NPM, do developers really gotta host these scripts to get paid?? They should be able to build their package, have some CDN like unpkg (though probably ours) consume it and spit it out. And probably do the JSONP stuff automatically for it--then make cloudflare foot the bill lol.

So--forgetting about the unpkg clone for now--basically all we're doing is this:

- tell regular developers to use our `contract-script` package, which has this component `<Script />`
- provide a simplified interface into our ethereum contract, allowing them to verify users are paying users + collect payments

From there, the question is do we wanna operate this thing centralized or decentralized. And I think we tackle it centralized to start, at least until our skills move beyond the simpler task of creating contracts. So basically what this entails is check our own internal servers if the user paid for the given plugin, and if so, display the plugin. If not, trigger the parent's payment facilities. And from there, to start at least, only the top level parent should handle payment UI/UX, while simply recording all children along the way to divvy out the cuts.

As we go, we'll likely have demand from people to get more decentralized, and for their plugin to exist outside of our ecosystem. Or, forks will be threatened (essentially taking our contracts and building their own ecosystem). Basically it's inevitable that a popular plugin who has many grand child plugins will not want to pay up the ladder if it can collect its own clients on its own. Or rather, perhaps they're happy to, but they also would like to have their own separate ecosystem. We can cross that bridge when we get to it :). 

To start, and to get our ethereum feet wet, we just want a simple authentication + multi-level payment scheme, with the database of plugins (and their relationships + prices, etc) stored centrally. Whatever it takes to ship something that makes money as soon as possible.

Check this piece:

https://medium.com/humanizing-the-singularity/2018-year-in-preview-the-future-of-cryptocurrency-b99110480ff0

There's a lot to takeaway there, but I think the biggest one is that to secure the future of Ethereum, there has to be actual UTILITY!!!! Nobody's using this shit. React developers seem clueless to everything going on in crypto world. Our entire business model here is essentially being the guys that introduce Ethereum to the JS application development crowd, which is like the biggest community of app developers. That's the whole go-to-market strategy of everything--to blow their minds with something that JUST MAKES SENSE AS THE PERFECT CONNECTION BETWEEN DAPPS + JS DEVELOPMENT. Done right will warrant tons of buzz.

But more importantly, if anyone's gonna pioneer the road forward of utility out of smart contracts, it's developers! The above article talks about how essentially the road forward requires us to provide so much value/utility to the world that regulators have no choice but to let ethereum/crypto live. The author talks about boeing jets and other big things being purchased with crpto. That's fine and dandy, but it starts with developers paying each other with it, which isn't happening yet. So we're the ones to do it. To show everyone how its done. 

These devtools will be like Wallabyjs' web panel. Im not sure if u've used it, but basically it opens up a page on wallabyjs.com, and then connects to a server running on your localhost that their VSCode plugin created. It then absorbs all the info about your tests and code from that server into a url on wallabyjs.com. The key point is a subtle one; it's that the devtools doesnt run on `localhost:3035` or something. We could do that, and ultimately it doesnt matter, but we want this to feel very solid. The way the Respond Framework devtools is brought to the user isnt as a chrome plugin. It's more like webpack-dev-server--you import our package and start the server. If the app is a universal app, we could do it without the user knowing when Respond is run on the server.

But also keep in mind, not all the tools need to connect to your host. Some plugins could be social plugins like chatrooms, user profiles, etc. ..Im kinda getting off track. The point is it's not a problem to connect another browser tab to what's going on in your app, just like Wallaby does with what's going on in VS Code. In fact, it's easier for us. 

So real point is simply that we'll make it commonplace to have another browser tab as your devtools instead of a chrome extension. I find the chrome extension annoying. ..This tab will be the home of an ecosystem of tools to help you with UI development. It's deeply synced to the browser window containing your app. Inevitably it will become home to social tools, perhaps the github of the future. And we wont need to make any of this. We'll make the contracts, popularize the host, and own the foundation (the Respond Framework). Perhaps one day it could work without the Respond Framework, but the first batch of plugins will be stuff that enhances your Rudy + Remixx development. 

We'll make a killer API that make sit far easier to make the React devtools. Somebody else can make those tools. But really, there's so many tools that can be built to ease development. Take for instance those GUIs for webpack builds like Webpack Dashboard, that could be here too. The thing could talk to VS Code like wallaby does. Wallabyjs is the big influence here. We'll have a beautiful API for plugin authors to talk to react windows, to other hosts on the computer like stuff coming out of VS Code. We'll of course make it easy to get all the info about remixx state, react component trees. They can evaluate things in the context of application windows. We'll build anything and everything we can think of to make it as easy as possible for them to make plugins. React specific plugins primarily. Very early on will push the social plugins in one way or another. Some young buck will wanna do that. I dont have any interest. But basically this will inevitably become a more popular social playground than discord, spectrum, reddit, etc, for React developers--why leave when you're already here. The shit can go deep too: someone will eventually make a plugin so you can edit someone else's app remotely, similar to the features CodeSandBox just added. The only difference is : ours is better because we're not limited to the browser. People will find ways to edit code in VS Code. VS Code has that feature now or will soon anyway. We can probably make use of some APIs surrounding it. 

Anyway, the possibilities are endless. We start small with enhanced redux devtools + plugin API. I see it as a winning opportunity. What must be done first is we consolidate the React development space through the Respond Framework. It's a mess, React will have its *Rails moment* whether its the Respond Framework or something else. It won't always be this *ad hoc configure each and everything* mess that javascript is. I love it, but we can have our cake and eat it too--thats what CRA is. We're the super thorough full stack CRA. We're not Next.js which is just shitty express routing and a few code-splitting specific couplings. We're global-state-store coupled first and foremost. ..Every tool that comes into existence has a primary perspective; and then they try to bend every side task to that perspective. You see this on the homepage of every SaaS that comes into existence. Then the products with the broadest core perspective do the best. Code Splitting, as in Next.js, isnt the primary perspective of app development. It's state management. They offer nothing there. So we're bending all side goals to the perspective of state management + horizontal transitions (routes). And it doesnt take much bending. the V in MVC is pretty much a solved problem [by react]. State management kinda is, but it needs consolidating, and that's what we're doing. We own this, we get a few more people, we blog about it incessantly all summer, the magpies come running. Next year, on codementor, odesk, etc, you will no longer here people asking for "React" + "Redux" help. The goal is to make "Respond Framework" the hottest word. That's it. It's easy. U could call a shitty framework that and promote the hell out of it, and it would work. It's just the timing of the space. It's too late in fact. The reason I've assessed it's taken so long is simply that people are brainwashed by javascript being this super modular building block configure everything ecosystem. Like, the pro developers here don't care to consolidate cuz they are brainwashed. Im not talkin about learners. They clearly think a Rails doesnt make sense here. Why would it, things like Meteor, Sails, etc, essentially are dead. The difference is Respond Framework doesn't discard the ideals of unix style building blocks + modularity. It's simply a collection of cohesive packages, but "packaged"/marketed properly as a singular group u have to learn. 

So that's why there's minimal competition here. Well that, and the fact that javascript fatigue really did seem to tire people out and people somehow got the idea that Redux completed the React pyramid. wrong. That's just the M and the V. Rudy is the C. Remixx is the improved M. There's actually a strategy to replace the V too. Not really, just a babel plugin for react called "react modern" that lets you code all of react as functions, eg: `MyComponent({ open: true }, [Child({foo: 'bar'}])`.

Everyone's asleep at the wheel my friend. They aren't seeing the big picture of what the ecosystem needs. You probably have heard the startup wisdom about "unbundling" and "bundling" product categories is how new product categories emerge, right. A framework is essentially *bundling*, but the funny thing is webpack will die through an *unbundling* (note: this is tangent). You were originally wanting to get better re-use out of modules in chunks. The problem is solved through the unbundling/unchunking of those modules.

For the landscape for all this shit is obvious for anyone not micro-focused, who has the time, and has been around long enough. And ultimately the future is really marvelous--we're almost at a point I wish I was always developing at. Like, once we reach this point, there's almost zero cruft; just pure business logic. We're gonna have to clean up some things with React Native navigators to make them bend to this declarative state driven perspective (rather than the current direction of React Navigation). Someone's gonna have to complete this project: https://github.com/wix/react-native-interactable. But otherwise, I dont see anything besides what Chris Granger was recently doing with Even and prolog until he gave up. UI development will finally be a solved problem. Primarily thanks to the React team. But we'll be the group that packages it up for proper consumption (bundling).

Here's another thread where more of the vision is shared: https://github.com/theKashey/memoize-state/issues/5#issuecomment-372543533

**Comment by faceyspacey** [comment]
> I was able to bring up the dns component which meant that the client wouldn’t need a domain at all to query for peers, instead it could download images via its own dns gateway and service worker to actually act as a server. 

Can you tell me more about that `dns component`?

> I then terminated the browser, killing the only seed, waited a few days and was still able to download it.

How is it able to get files when there are no other users connected? Cloudflare's new server worker thing?

**Comment by faceyspacey** [comment]
> I just don't understand why webpack resources cannot be shared or over the wire. Wether I build them or load them externally, why can 5 webpack builds sit on the same page and load resources over the wire and share their dependencies with other builds on the FE.

Forgetting the unbundling back to modules thing for a moment, I think part of the problem is that webpack *wraps* modules in specific code needed to run. That wrapping can change. For example if you're using `imports-loader` you can in a real context for `this`/`window` instead of the dummy object they give you. But in standard builds it's likely the same for most apps. So if each module was pre-wrapped (similar to what package developers do when creating a UMD build), and if module IDs were deterministic by default, then webpack could more naturally integrate what we currently solve with things like `externals` and the `ProvidePlugin`.

The webpack codebase is large and does so many things, and they obviously have tons on their plate. But basically I think you're right here--that a *rethink* could do some serious justice when it comes to importing/loading arbitrary modules. I went through hell recently on a client project making lots of legacy global javascript code work properly. I think the way the webpack team sees it is they want everyone to conform to their ES6 modules approach. I mean they definitely dont give a shit about those legacy globals stuff. Things like externals and all that jazz is very unreliable. U better be using the webpack stats analyzer (the pie chart visualizer and their internal tool) to see what's actually getting bundled, and what module requests are actually being made, or ur gonna end up with modules you werent expecting. Im sure u know. Then u gotta filter requests with functions in ur configs, etc. 

But, what they should care about is making it easy to bring your own modules, while ignoring them if you mark them as such. I think the problem lies in how much build time it would take to produce scripts for all the possible combinations you might have. Cuz just to do some of the things u mentioned might require a chunk of react + redux + foo sometimes, and then another times just react + redux, which means foo has to be its separate chunk as well to achieve maximum efficiency from the end user's perspective. At which point, the only real solution is completely unbundling, which isnt a solution in the minds of most developers. ...Basically, there should be a mode in production where it calculates all the different possible chunk combinations, and will create a chunk that just contains foo, for example. For webpack 4, they've given us a lot more control on where modules end up, but I don't think modules appearing in multiple (or many) chunks is on the agenda. I forget, but maybe it can appear in a few, but it's not super smart in that its calculating the *difference* between chunks and then generating new chunks based on that. That would sky rocket the number of chunks that gotta be generated, and they certainly aren't going there *yet*. Probably never.

**Comment by faceyspacey** [comment]
As far as the licensing issues go, your eons beyond me. Honestly it sounds like you have a perfect grasp how to handle that when it gets to it. I'm otherwise clueless. Your work with service workers in general is very interesting to me. I'm behind in understanding service workers. I've studied them for a few hours, but haven't reach a level where I have any ideas for novel implementations/usages. They do sound like a good place to handle the securing of our licensing.

**Comment by faceyspacey** [comment]
> I was speaking with some of my engineers today about the idea of code splitting and on the wire from a third party. One big question that came up, which I think is relevant in this context. How'd you tree shake something like this, and remove bloat from... well essentially a similar sounding architecture im trying to lay? The script works on its own, but the script should be able to behave as a chunk too, lending it resources to another chunk. If you find yourself trying to solve this, as far as im aware - if or when we DO solve it… Boom another world first.

In the impending unbundled world, basically the script can load in 2 phases: 

- one where it checks what's already on the page
- and another where it gets what its missing

So for the first request, they send back just the list of modules they need. Then the `Script` component finds the difference and sends that back in a second request which sends back just the missing ones, in the same HTTP2 push way as in react-without-webpack.

I think if we mastered this approach, some opportunities could bridge the old world to this. I mean what if webpack simply shipped in production the best chunks it could create PLUS ALL MODULES. Then any time it could find some efficiencies where it only needed a few number of modules client side, it would just get those. Or basically, if it did the math and figured out all combinations, webpack could have a smart engine client side in production that finds the perfect smallest chunk it needs for every dynamic import.

With deterministic module IDs, you should just be able to make your chunks from a drag-n-drop editor lol. And then from there, if u didnt make the chunk, webpack will simply throw an error client side when it goes to request a module entry.

So basically when requires are evaluated client side, it checks the cache, and if it's not in the cache, it treats it as an entry and requests it from the server. It's your job to make an entry by that name.

It's actually an interesting concept--leave it all in the developer's hands; and otherwise have a dumb require/import mechanism. Again, that just looks in the cache or requests it from the server *using deterministic module IDs* for both entry chunks/scripts + moudle IDs themselves.

That would leave it up to the developer to make application-specific "smart chunks" that only bring along the modules likely needed. 

----

If you dont need crazy loaders and plugins, resolving deps client side is primarily rewriting `require` to do whatever we want. For example, if all the deps are on the page, `require` simply recursively grabs deps out of a hash until an "entry module" is ready. But if it doesn't have them, it's a problem without a rendering mechanism that can adjust for this. So static imports wouldnt work, as that happens before rendering even begins. This goes back to what you were saying with doing `import()` everywhere. If modules were only acquired right where they are used, eg:

```js
async componentDidMount() {
   const SomeComponent = await import('./SomeComponen't).default
   this.setState({ SomeComponent })
}

render() {
    const { SomeComponent } = this.state
    return SomeComponent ? <SomeComponent /> : <Spinner />
}
```
Then we can get around the static imports problem.

What about utility functions and things that arent components?

That basically means all functions in userland must be async. Cuz u may have to wait on a promise to get it.

----

But from there, it's just up to you to package together your modules into accurate and complete "smart chunks."

Though actually, that's not complete. You may have an entry that you need, but already contains some modules you already have. So you need 2 entries, as we've been discussing. How do you differentiate between the two. This may go back to the same concept with `<Script />` where 2 requests must be made (this time slightly different): one with a response with what chunks are available and whats in the chunks, and then a 2nd where the client picks a chunk.

Perhaps a slicker more automatic algorithm could be devised. Perhaps as part of the drag-n-drop chunk builder, you can generate some JSON that represents such a decision tree, and done.

----

What webpack is doing is very complex because it tries to be anything and everything to everyone. If you were ok with some manual labor here, you could create your own chunks, and write some "bootstrap" code + custom functions for requires and dynamic imports that operate on  your hash of chunks + decision tree. You will have to follow the import deps graph in a node script tho--i.e. to initially find the complete set of modules being used. Well, u dont have to do that, but u probably want to.

----

The interesting part is we may even be able to avoid having to add any wrapping/bundling code if we code our app a certain way. I.e. if we only used `import()` within runtime functions (or perhaps used our own function like `importAsync()` if the browser didnt like the first one), then we could just provide this function client side, and it would do the above logic to get the appropriate chunk or module. In short, we offload the work to how we write our app. If the app is all built out of async/await functions and `import()`, then it's all about:

- A) creating chunks/scripts by the appropriate names
- B) writing the `import()` function to smartly request the smartest chunk

Then we have a simple GUI which shows all the modules in your app (in the MVP, its all of NODE_MODULES, and ur entire project's file system). And you can create chunk buckets and put modules into each. A module will highlight if its in a chunk, and a number to its right will appear telling u how many chunks its in (to give u an idea of how smartly ur putting it to use).

Then your chunk scripts are concatenated with modules receiving deterministic IDs. No webpack style bundle transformation happens. Or at least very minimal--module exports are just assigned to a hash. And if u want to transform it with babel u can.

----

That would be the MVP. Obviously if u miss a module, it will break. In the future we can provide some intelligence that helps prevent that. There's probably several ways to skin that cat. One way to never fail is to always have all modules individually on deck as a last resort, which might lead to lots of requests, but and a long wait time (since each module will have to load in the browser before the next set of modules is requested), but at least it wouldnt fail.

...The webpack people would be so pissed if something this simple worked and became popular. The magic is all in the fact that people simply started using `import()` EVERYWHERE like they wanted lol. And that async/await is used everywhere.

**Comment by faceyspacey** [comment]
One other idea: instead of an interface to create chunks, the devtools could have a plugin that tracks which modules end up being needed in the same `import()` batch, and then it could recommend a chunk to make (perhaps multiple chunks to make), and then you click a button and JSON representation is generated in a file in your project directory. Then later you can execute a command that creates chunks based on all those json snapshots.

So, during development you would never be dealing with chunks, as that would slow build time. You have HTTP2 push all setup and your always getting individual modules, but as you develop you can use the plugin interface to start to think about how you want to chunkify them for production.

This is similar to testing "sniping" interface, which makes writing tests interactive GUI-based *after the fact*. It makes it a process the user does as part of their workflow, rather than a *one and done* sorta thing.

Honestly, at first glance, this idea is seeming phenomenal. And not that hard to build. You just gotta write your app without static imports. Then the first real thing we gotta code--after putting react-without-webpack to use--is a bootstrap script that fills in your hash of modules.

Another aspect is this: during development, you dont want to wait for sequential module loading. So similar to the chunk creation plugin just described, every time a module is first imported, we keep track of every child module it depends on, and we store a representation of those deps in the browser in localStorage. Then on reloads, it will get all the modules it thinks it needs in parallel. If you added a new module as a dep to one of the modules, it will be the only one that is sequentially retrieved; and then of course the localStorage representation will be updated.

The plugin would then pull up all these entries/chunks and their deps and let you further optimize them by creating additional chunks with shared modules + the decision tree about which entry chunk to request if multiple entries start with the same module. I.e. under certain conditions when you want entry `foo` u will grab entry `foo-a.js` and then when the parent issuing module/chunk is different u will get `foo-b.js`.

----
It's just one of those things where the solution is greatly simplified when approaching it from a different angle, or if different core capabilities are available to us.

If you think about it, most of our webpack usage is during development. That means a lot of webpack capabilities we are using are geared towards development. *However* completely different (and better) capabilities are available to us when we are in development mode in the latest version of Chrome/canary[ with experimental features perhaps turned on ]. We shouldnt let production limitations effect development "bundling" so much. That said, this can obviously lead to production-only bugs. But for an app with a proper test suite it's not that big of an issue.

Im personally fine waiting a while for production builds to build. It's all about development build times. But I know large companies with huge apps dont want their ci taking forever to build every possible combination of chunks. That said, it's now doing less work, and now simpler concatenation. We can also make our system smarter on CI so it doesn't waste time even touching cached chunks that rarely change. Optimization is obviously something that comes last, and it's probably no big deal.

It's just crazy to think that coding your app a little bit differently reduces tens of thousands of lines of unnecessary webpack code. But it wouldnt be a first. "Code Split by Default" is essentially the slogan here.

----
I know Ives at CodeSandBox built his own bundler et al. They have constrained needs. Again, when we dont have to be everything to everyone, we can achieve our goals in a fraction the time/code. Webpack still has to support all sorts of legacy setups, bundling strategies, loaders, plugins. We're loader-free because we are targeted towards the Respond Framework which uses css-in-js components. We start out with a few weak areas like no file-loader, but that's really not that big of a deal, especially when you can individually invalidate the cache for individual images in cloudinary. And keep in mind, it's a small number of brand images, not user-uploaded images which have proper hashes which change on S3 and in the db when updated. I didnt even use file-loader until this past year. I do appreciate it now though.

..Im just thinking what else do we need?? 90% of the webpack plugins are solutions to their own problems, problems we no longer have thanks to unbundling.

----

This is an area I did not plan to tackle, but definitely could be another order of magnitude shift (or half of one) that defines our *superior approach* :)

..Anyway, 10,000 ideas, only 10 hours. ..I feel like the best developers moved to blockchain, and everyone left in UI/app development just settled on react/redux/graphql *as it is* as the end of the story. When that's simply not the case. This is just a big gaping set of needs for us stragglers to fix. There's a lot of evolving conditions to be taken advantage of in what amounts to the biggest space of developers. Let the boy geniuses tackle machine learning, blockchain, etc. There's money to be made cleaning up traditional app development where droves of new developers are flocking to, given how easy it has become. Put the bow on top and complete the vision of simple business logic here, and we can quit our jobs knowing we were the ones that finally made software development something anyone can do.

ps. make sure to read that link above from theKashey's repo. I outline a whole other thread about how to teach programming/react/js--basically by teaching how to make a grocery shopping list, and how a nested to do list comprised of functions is all that react/html layouts are. It focuses on the concept that react could just be functions instead of HTML, which in combination with css-in-js components (specifically Glamorous and Emotion using object syntax), means new developers just have to learn JS. Not HTML + CSS + JSX + JS + SERVER STUFF. Basically developers just need to learn functional components + basic logic (and Rudy's route API), and they can build the moon. We're on the verge of making application development as simple as it possibly can be. We and many like us will be out of a job or have to accept major pay decreases--but at least we'll be the ones that capitalized on teaching the next generation. This stuff is just too easy now. But that means a huge market to teach it to.
